[project]
name = "personal-finance-analyser"
version = "0.1.0"
description = "Datawarehouse and datascience for financial statements"
readme = "README.md"
requires-python = ">=3.13.2"
dependencies = []
